wandb_version: 1

_content:
  desc: null
  value:
    config: cfg.yaml
    dataset: '{''name'': ''coco'', ''params'': {''train_path'': ''/media/pranoy/UBUNTU_ROOT/home/pranoy/datasets/coco2017'',
      ''val_path'': None, ''num_workers'': 4, ''pin_memory'': True, ''batch_size'':
      8, ''persistent_workers'': True, ''shuffle'': True, ''train_test_split'': 0.9},
      ''preprocessing'': {''resolution'': 512, ''center_crop'': False, ''random_flip'':
      False, ''random_crop'': False}}'
    experiment: '{''name'': ''run1'', ''project_name'': ''Yolo'', ''output_folder'':
      ''outputs/yolo'', ''max_train_examples'': 1000000, ''save_every'': 1000, ''eval_every'':
      500, ''sample_every'': 1000, ''log_every'': 100, ''log_level'': ''info'', ''resume_path_from_checkpoint'':
      None}'
    lr_scheduler: '{''scheduler'': ''cosine_with_warmup'', ''params'': {''learning_rate'':
      ''${optimizer.params.learning_rate}'', ''warmup_steps'': 100}}'
    model: '{''name'': ''yolo'', ''dim'': 512, ''transformer'': {''dim'': 512, ''patch_size'':
      8, ''n_heads'': 8, ''d_head'': 64, ''depth'': 8, ''dropout'': 0.1, ''mlp_dim'':
      2048}}'
    optimizer: '{''name'': ''adamw'', ''params'': {''learning_rate'': 0.0001, ''beta1'':
      0.9, ''beta2'': 0.999, ''weight_decay'': 0.0, ''epsilon'': 1e-08}}'
    training: '{''gradient_accumulation_steps'': 1, ''mixed_precision'': ''no'', ''seed'':
      42, ''num_epochs'': 200}'
_flags_cache:
  desc: null
  value:
    struct: null
_metadata:
  desc: null
  value: ContainerMetadata(ref_type=typing.Any, object_type=<class 'dict'>, optional=True,
    key=None, flags={}, flags_root=False, resolver_cache=defaultdict(<class 'dict'>,
    {}), key_type=typing.Any, element_type=typing.Any)
_parent:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.34.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.12
    start_time: 1706380191
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      - 71
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      - 71
      3:
      - 13
      - 16
      4: 3.10.12
      5: 0.12.21
      6: 4.34.0.dev0
      8:
      - 5
